[package]
name = "hausmaus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
openssl = { version = "0.10.45", features = ["vendored"] }
openssl-sys = "0.9.80"
paho-mqtt = "0.12.0"

[dev-dependencies]
tempdir = "0.3.7"
