name: Build for ARM
on:
  workflow_dispatch:

jobs:
  xcompile:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release
      - uses: actions/upload-artifact@v3
        with:
          name: arm
          retention-days: 7
          path: |
            target/armv7-unknown-linux-gnueabihf/release/hausmaus
